name: ai_plant_doctor
description: "AI Plant Doctor - Detect plant diseases and protect agriculture."
publish_to: 'none' # Remove if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4

  # UI + Icons
  cupertino_icons: ^1.0.8

  # Image Picker (Camera + Gallery)
  image_picker: ^1.0.7

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2



  shared_preferences: ^2.2.1

flutter:
  uses-material-design: true

  # ðŸ‘‡ Register your assets here
  assets:
    - assets/bg.jpg
    - assets/google.png
    - assets/facebook.png
    - assets/scan.png
    - assets/scan_placeholder.png
    - assets/tomato.png
    - assets/wheat.png
    - assets/plant.png



